server:
  port: 8090
#  servlet:
#    context-path: /hisystem
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hisystem?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password:
    username: 1208585122@qq.com
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  #热部署(若html或js有更改，要开启浏览器自动刷新功能，先禁用浏览器缓存，使用LiveReload插件)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true